---
title: Greg Atkin
baseurl: "/"
permalink: "/:title/"
layout_style: overflow
palette: green
header:
  title: ''
  tagline: ''
  profile_img: "/images/7703602 10.08.53 AM.jpg"
  bg: dark
  has_nav: true
  has_social: true
footer:
  content: "&copy; Stackbit-Fresh. All rights reserved."
  links:
  - text: Made with Stackbit
    url: https://www.stackbit.com
    new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
- jekyll-menus
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- ssg-build.sh
- LICENSE.md
- README.md
- netlify.toml
collections:
  posts:
    permalink: "/posts/:title/"
